# Generated by Django 5.2.7 on 2025-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['word', 'definition'], name='dictionary__word_12b5c8_idx')],
            },
        ),
    ]
